// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filedata.proto

#include "filedata.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_filedata_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_FilePerson_filedata_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_filedata_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FilePerson_FileProperties_filedata_2eproto;
namespace projectstructure {
class FilePerson_FilePropertiesDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FilePerson_FileProperties> _instance;
} _FilePerson_FileProperties_default_instance_;
class FilePersonDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FilePerson> _instance;
} _FilePerson_default_instance_;
class FilePersonBookDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FilePersonBook> _instance;
} _FilePersonBook_default_instance_;
}  // namespace projectstructure
static void InitDefaultsscc_info_FilePerson_filedata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::projectstructure::_FilePerson_default_instance_;
    new (ptr) ::projectstructure::FilePerson();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::projectstructure::FilePerson::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_FilePerson_filedata_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_FilePerson_filedata_2eproto}, {
      &scc_info_FilePerson_FileProperties_filedata_2eproto.base,}};

static void InitDefaultsscc_info_FilePerson_FileProperties_filedata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::projectstructure::_FilePerson_FileProperties_default_instance_;
    new (ptr) ::projectstructure::FilePerson_FileProperties();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::projectstructure::FilePerson_FileProperties::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FilePerson_FileProperties_filedata_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_FilePerson_FileProperties_filedata_2eproto}, {}};

static void InitDefaultsscc_info_FilePersonBook_filedata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::projectstructure::_FilePersonBook_default_instance_;
    new (ptr) ::projectstructure::FilePersonBook();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::projectstructure::FilePersonBook::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_FilePersonBook_filedata_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_FilePersonBook_filedata_2eproto}, {
      &scc_info_FilePerson_filedata_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_filedata_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_filedata_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_filedata_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_filedata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePerson_FileProperties, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePerson_FileProperties, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePerson_FileProperties, fileid_),
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePerson_FileProperties, filename_),
  1,
  0,
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePerson, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePerson, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePerson, userid_),
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePerson, file_),
  0,
  ~0u,
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePersonBook, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePersonBook, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::projectstructure::FilePersonBook, people_),
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::projectstructure::FilePerson_FileProperties)},
  { 9, 16, sizeof(::projectstructure::FilePerson)},
  { 18, 24, sizeof(::projectstructure::FilePersonBook)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::projectstructure::_FilePerson_FileProperties_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::projectstructure::_FilePerson_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::projectstructure::_FilePersonBook_default_instance_),
};

const char descriptor_table_protodef_filedata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016filedata.proto\022\020projectstructure\"\213\001\n\nF"
  "ilePerson\022\016\n\006userid\030\001 \002(\005\0229\n\004file\030\002 \003(\0132"
  "+.projectstructure.FilePerson.FileProper"
  "ties\0322\n\016FileProperties\022\016\n\006fileid\030\001 \002(\005\022\020"
  "\n\010filename\030\002 \002(\t\">\n\016FilePersonBook\022,\n\006pe"
  "ople\030\001 \003(\0132\034.projectstructure.FilePerson"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_filedata_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_filedata_2eproto_sccs[3] = {
  &scc_info_FilePerson_filedata_2eproto.base,
  &scc_info_FilePerson_FileProperties_filedata_2eproto.base,
  &scc_info_FilePersonBook_filedata_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_filedata_2eproto_once;
static bool descriptor_table_filedata_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_filedata_2eproto = {
  &descriptor_table_filedata_2eproto_initialized, descriptor_table_protodef_filedata_2eproto, "filedata.proto", 240,
  &descriptor_table_filedata_2eproto_once, descriptor_table_filedata_2eproto_sccs, descriptor_table_filedata_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_filedata_2eproto::offsets,
  file_level_metadata_filedata_2eproto, 3, file_level_enum_descriptors_filedata_2eproto, file_level_service_descriptors_filedata_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_filedata_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_filedata_2eproto), true);
namespace projectstructure {

// ===================================================================

void FilePerson_FileProperties::InitAsDefaultInstance() {
}
class FilePerson_FileProperties::_Internal {
 public:
  using HasBits = decltype(std::declval<FilePerson_FileProperties>()._has_bits_);
  static void set_has_fileid(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_filename(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

FilePerson_FileProperties::FilePerson_FileProperties()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:projectstructure.FilePerson.FileProperties)
}
FilePerson_FileProperties::FilePerson_FileProperties(const FilePerson_FileProperties& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_filename()) {
    filename_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.filename_);
  }
  fileid_ = from.fileid_;
  // @@protoc_insertion_point(copy_constructor:projectstructure.FilePerson.FileProperties)
}

void FilePerson_FileProperties::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FilePerson_FileProperties_filedata_2eproto.base);
  filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  fileid_ = 0;
}

FilePerson_FileProperties::~FilePerson_FileProperties() {
  // @@protoc_insertion_point(destructor:projectstructure.FilePerson.FileProperties)
  SharedDtor();
}

void FilePerson_FileProperties::SharedDtor() {
  filename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void FilePerson_FileProperties::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FilePerson_FileProperties& FilePerson_FileProperties::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FilePerson_FileProperties_filedata_2eproto.base);
  return *internal_default_instance();
}


void FilePerson_FileProperties::Clear() {
// @@protoc_insertion_point(message_clear_start:projectstructure.FilePerson.FileProperties)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    filename_.ClearNonDefaultToEmptyNoArena();
  }
  fileid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* FilePerson_FileProperties::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required int32 fileid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_fileid(&has_bits);
          fileid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required string filename = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_filename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "projectstructure.FilePerson.FileProperties.filename");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FilePerson_FileProperties::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:projectstructure.FilePerson.FileProperties)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 fileid = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_fileid(), target);
  }

  // required string filename = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_filename().data(), static_cast<int>(this->_internal_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "projectstructure.FilePerson.FileProperties.filename");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_filename(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:projectstructure.FilePerson.FileProperties)
  return target;
}

size_t FilePerson_FileProperties::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:projectstructure.FilePerson.FileProperties)
  size_t total_size = 0;

  if (_internal_has_filename()) {
    // required string filename = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename());
  }

  if (_internal_has_fileid()) {
    // required int32 fileid = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_fileid());
  }

  return total_size;
}
size_t FilePerson_FileProperties::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:projectstructure.FilePerson.FileProperties)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string filename = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename());

    // required int32 fileid = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_fileid());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FilePerson_FileProperties::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:projectstructure.FilePerson.FileProperties)
  GOOGLE_DCHECK_NE(&from, this);
  const FilePerson_FileProperties* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FilePerson_FileProperties>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:projectstructure.FilePerson.FileProperties)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:projectstructure.FilePerson.FileProperties)
    MergeFrom(*source);
  }
}

void FilePerson_FileProperties::MergeFrom(const FilePerson_FileProperties& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:projectstructure.FilePerson.FileProperties)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      filename_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.filename_);
    }
    if (cached_has_bits & 0x00000002u) {
      fileid_ = from.fileid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void FilePerson_FileProperties::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:projectstructure.FilePerson.FileProperties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FilePerson_FileProperties::CopyFrom(const FilePerson_FileProperties& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:projectstructure.FilePerson.FileProperties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FilePerson_FileProperties::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void FilePerson_FileProperties::InternalSwap(FilePerson_FileProperties* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  filename_.Swap(&other->filename_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(fileid_, other->fileid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FilePerson_FileProperties::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void FilePerson::InitAsDefaultInstance() {
}
class FilePerson::_Internal {
 public:
  using HasBits = decltype(std::declval<FilePerson>()._has_bits_);
  static void set_has_userid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

FilePerson::FilePerson()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:projectstructure.FilePerson)
}
FilePerson::FilePerson(const FilePerson& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      file_(from.file_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  userid_ = from.userid_;
  // @@protoc_insertion_point(copy_constructor:projectstructure.FilePerson)
}

void FilePerson::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FilePerson_filedata_2eproto.base);
  userid_ = 0;
}

FilePerson::~FilePerson() {
  // @@protoc_insertion_point(destructor:projectstructure.FilePerson)
  SharedDtor();
}

void FilePerson::SharedDtor() {
}

void FilePerson::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FilePerson& FilePerson::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FilePerson_filedata_2eproto.base);
  return *internal_default_instance();
}


void FilePerson::Clear() {
// @@protoc_insertion_point(message_clear_start:projectstructure.FilePerson)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  file_.Clear();
  userid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* FilePerson::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required int32 userid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_userid(&has_bits);
          userid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .projectstructure.FilePerson.FileProperties file = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_file(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FilePerson::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:projectstructure.FilePerson)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 userid = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_userid(), target);
  }

  // repeated .projectstructure.FilePerson.FileProperties file = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_file_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_file(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:projectstructure.FilePerson)
  return target;
}

size_t FilePerson::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:projectstructure.FilePerson)
  size_t total_size = 0;

  // required int32 userid = 1;
  if (_internal_has_userid()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_userid());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .projectstructure.FilePerson.FileProperties file = 2;
  total_size += 1UL * this->_internal_file_size();
  for (const auto& msg : this->file_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FilePerson::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:projectstructure.FilePerson)
  GOOGLE_DCHECK_NE(&from, this);
  const FilePerson* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FilePerson>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:projectstructure.FilePerson)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:projectstructure.FilePerson)
    MergeFrom(*source);
  }
}

void FilePerson::MergeFrom(const FilePerson& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:projectstructure.FilePerson)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  file_.MergeFrom(from.file_);
  if (from._internal_has_userid()) {
    _internal_set_userid(from._internal_userid());
  }
}

void FilePerson::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:projectstructure.FilePerson)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FilePerson::CopyFrom(const FilePerson& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:projectstructure.FilePerson)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FilePerson::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(file_)) return false;
  return true;
}

void FilePerson::InternalSwap(FilePerson* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  file_.InternalSwap(&other->file_);
  swap(userid_, other->userid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FilePerson::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void FilePersonBook::InitAsDefaultInstance() {
}
class FilePersonBook::_Internal {
 public:
  using HasBits = decltype(std::declval<FilePersonBook>()._has_bits_);
};

FilePersonBook::FilePersonBook()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:projectstructure.FilePersonBook)
}
FilePersonBook::FilePersonBook(const FilePersonBook& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      people_(from.people_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:projectstructure.FilePersonBook)
}

void FilePersonBook::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FilePersonBook_filedata_2eproto.base);
}

FilePersonBook::~FilePersonBook() {
  // @@protoc_insertion_point(destructor:projectstructure.FilePersonBook)
  SharedDtor();
}

void FilePersonBook::SharedDtor() {
}

void FilePersonBook::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FilePersonBook& FilePersonBook::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FilePersonBook_filedata_2eproto.base);
  return *internal_default_instance();
}


void FilePersonBook::Clear() {
// @@protoc_insertion_point(message_clear_start:projectstructure.FilePersonBook)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  people_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* FilePersonBook::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .projectstructure.FilePerson people = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_people(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FilePersonBook::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:projectstructure.FilePersonBook)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .projectstructure.FilePerson people = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_people_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_people(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:projectstructure.FilePersonBook)
  return target;
}

size_t FilePersonBook::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:projectstructure.FilePersonBook)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .projectstructure.FilePerson people = 1;
  total_size += 1UL * this->_internal_people_size();
  for (const auto& msg : this->people_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FilePersonBook::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:projectstructure.FilePersonBook)
  GOOGLE_DCHECK_NE(&from, this);
  const FilePersonBook* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FilePersonBook>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:projectstructure.FilePersonBook)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:projectstructure.FilePersonBook)
    MergeFrom(*source);
  }
}

void FilePersonBook::MergeFrom(const FilePersonBook& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:projectstructure.FilePersonBook)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  people_.MergeFrom(from.people_);
}

void FilePersonBook::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:projectstructure.FilePersonBook)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FilePersonBook::CopyFrom(const FilePersonBook& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:projectstructure.FilePersonBook)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FilePersonBook::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(people_)) return false;
  return true;
}

void FilePersonBook::InternalSwap(FilePersonBook* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  people_.InternalSwap(&other->people_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FilePersonBook::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace projectstructure
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::projectstructure::FilePerson_FileProperties* Arena::CreateMaybeMessage< ::projectstructure::FilePerson_FileProperties >(Arena* arena) {
  return Arena::CreateInternal< ::projectstructure::FilePerson_FileProperties >(arena);
}
template<> PROTOBUF_NOINLINE ::projectstructure::FilePerson* Arena::CreateMaybeMessage< ::projectstructure::FilePerson >(Arena* arena) {
  return Arena::CreateInternal< ::projectstructure::FilePerson >(arena);
}
template<> PROTOBUF_NOINLINE ::projectstructure::FilePersonBook* Arena::CreateMaybeMessage< ::projectstructure::FilePersonBook >(Arena* arena) {
  return Arena::CreateInternal< ::projectstructure::FilePersonBook >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
